version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn BaseballStatPredictor_project.wsgi:application --bind 0.0.0.0:39821 --timeout 120"
    volumes:
      - .:/app
    ports:
      - 39821:39821
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: BaseballStatPredictor-web
    environment:
      - OPENBLAS_NUM_THREADS=1

  db:
    image: postgres:17-alpine
    restart: always
    container_name: Baseball-Stat-Predictor-db
    volumes:
#      - postgres_data:/var/lib/postgresql/data
      - /home/bmclean2/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "39822:5432"

  pgadmin:
    container_name: pgadmin4_container_BaseballStatPredictor
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "39823:80"

volumes:
  postgres_data: