# Generated by Django 5.1.1 on 2024-10-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStatPredictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadToHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('game_id', models.IntegerField()),
                ('team', models.CharField()),
            ],
        ),
    ]
