# Generated by Django 5.1.1 on 2024-10-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStatPredictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
