# Generated by Django 5.1.1 on 2024-10-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStatPredictor', '0002_alter_user_email_alter_user_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.CharField(unique=True),
        ),
    ]
