# Generated by Django 5.1.1 on 2024-10-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStatPredictor', '0002_headtohead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField()),
                ('opponent', models.CharField()),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('doubles', models.IntegerField(blank=True, null=True)),
                ('triples', models.IntegerField(blank=True, null=True)),
                ('home_runs', models.IntegerField(blank=True, null=True)),
                ('rbis', models.IntegerField(blank=True, null=True)),
                ('walks', models.IntegerField(blank=True, null=True)),
                ('strike_outs', models.IntegerField(blank=True, null=True)),
                ('innings_pitched', models.IntegerField(blank=True, null=True)),
                ('hits_allowed', models.IntegerField(blank=True, null=True)),
                ('runs_allowed', models.IntegerField(blank=True, null=True)),
                ('earned_runs', models.IntegerField(blank=True, null=True)),
                ('home_runs_allowed', models.IntegerField(blank=True, null=True)),
                ('pitches_thrown', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
