# Generated by Django 5.1.1 on 2024-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStatPredictor', '0003_playerstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='innings_pitched',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
