# Generated by Django 5.1.1 on 2024-10-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStatPredictor', '0004_alter_playerstats_innings_pitched'),
    ]

    operations = [
        migrations.AddField(
            model_name='headtohead',
            name='email',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='email',
            field=models.CharField(default=''),
        ),
    ]
