# Generated by Django 5.1.1 on 2024-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseballStatPredictor', '0005_headtohead_email_playerstats_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headtohead',
            name='email',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='email',
            field=models.CharField(),
        ),
    ]
